[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "deny"
ignore = []

[licenses]
version = 2
private = { ignore = true }
allow = [
    "Apache-2.0",
    "MIT",
    "MPL-2.0",
]

[sources]
unknown-git = "deny"
allow-git = []